<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\IUser.cs" />
    <Compile Remove="ProjectDbContext.cs" />
    <Compile Remove="Services\UserSevice.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrderUp.Domain\OrderUp.Domain.csproj" />
    <ProjectReference Include="..\OrderUp.Persistence\OrderUp.Persistence.csproj" />
  </ItemGroup>

</Project>
